// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sankore.Modules.Leads.Infrastructure;

#nullable disable

namespace Sankore.Modules.Leads.Infrastructure.Migrations
{
    [DbContext(typeof(LeadsDbContext))]
    [Migration("20260919125228_AddCrmTasksAndGenerationRules")]
    partial class AddCrmTasksAndGenerationRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("leads")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.CrmTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_agent_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("SlaDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("TriggerEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_event_id");

                    b.Property<string>("TriggerEventType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_event_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_crm_tasks");

                    b.HasIndex("AssignedAgentId", "Status")
                        .HasDatabaseName("ix_crm_tasks_assigned_agent_id_status");

                    b.HasIndex("LeadId", "Status")
                        .HasDatabaseName("ix_crm_tasks_lead_id_status");

                    b.HasIndex("TenantId", "Status", "DueAt")
                        .HasDatabaseName("ix_crm_tasks_tenant_id_status_due_at");

                    b.ToTable("crm_tasks", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.DispatchingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AntiMonopolyThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("anti_monopoly_threshold");

                    b.Property<string>("ExcludedAgentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("excluded_agent_ids");

                    b.Property<TimeSpan>("FirstContactSla")
                        .HasColumnType("interval")
                        .HasColumnName("first_contact_sla");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxLeadsPerAgent")
                        .HasColumnType("integer")
                        .HasColumnName("max_leads_per_agent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_dispatching_rules");

                    b.HasIndex("TenantId", "Strategy", "IsActive", "Priority")
                        .HasDatabaseName("ix_dispatching_rules_tenant_id_strategy_is_active_priority");

                    b.ToTable("dispatching_rules", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.DuplicateDismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_lead_id");

                    b.Property<DateTimeOffset>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<Guid>("DismissedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("dismissed_by");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_duplicate_dismissals");

                    b.HasIndex("TenantId", "LeadId", "CandidateLeadId")
                        .IsUnique()
                        .HasDatabaseName("ix_duplicate_dismissals_tenant_id_lead_id_candidate_lead_id");

                    b.ToTable("duplicate_dismissals", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid?>("AgentCollectedLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_collected_lead_id");

                    b.Property<string>("Campaign")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("campaign");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("Channel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("channel");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_email");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("company_phone");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("converted_at");

                    b.Property<Guid?>("ConvertedToCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_to_customer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentAssignedId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_assigned_id");

                    b.Property<Guid?>("CurrentAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_assignment_id");

                    b.Property<string>("CustomerReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_reference");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_reference");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("IntentLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("intent_level");

                    b.Property<string>("InterestedProduct")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("interested_product");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("LossReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("loss_reason");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("national_id");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PipelineStage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("pipeline_stage");

                    b.Property<Guid?>("PreferredAgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_agency_id");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("ProspectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prospect_type");

                    b.Property<double>("QualificationCompleteness")
                        .HasColumnType("double precision")
                        .HasColumnName("qualification_completeness");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_leads_expires_at");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_leads_full_name");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_leads_phone_number");

                    b.HasIndex("TenantId", "CustomerReference")
                        .HasDatabaseName("ix_leads_tenant_id_customer_reference")
                        .HasFilter("customer_reference IS NOT NULL");

                    b.HasIndex("TenantId", "NationalId")
                        .HasDatabaseName("ix_leads_tenant_id_national_id")
                        .HasFilter("national_id IS NOT NULL");

                    b.HasIndex("TenantId", "PipelineStage")
                        .HasDatabaseName("ix_leads_tenant_id_pipeline_stage");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_leads_tenant_id_status");

                    b.ToTable("leads", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Outcome")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_lead_activities");

                    b.HasIndex("LeadId", "PerformedAt")
                        .HasDatabaseName("ix_lead_activities_lead_id_performed_at");

                    b.HasIndex("TenantId", "LeadId")
                        .HasDatabaseName("ix_lead_activities_tenant_id_lead_id");

                    b.ToTable("lead_activities", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("CompatibilityFactorsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("compatibility_factors_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<double>("CompatibilityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("compatibility_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FirstContactAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_contact_at");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text")
                        .HasColumnName("override_reason");

                    b.Property<DateTimeOffset>("SlaDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("WasManualOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("was_manual_override");

                    b.HasKey("Id")
                        .HasName("pk_lead_assignments");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_lead_assignments_agent_id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_lead_assignments_lead_id");

                    b.HasIndex("SlaDeadline", "FirstContactAt")
                        .HasDatabaseName("ix_lead_assignments_sla_deadline_first_contact_at");

                    b.ToTable("lead_assignments", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("ProofReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("proof_reference");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("WithdrawalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("withdrawal_reason");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.Property<Guid?>("WithdrawnBy")
                        .HasColumnType("uuid")
                        .HasColumnName("withdrawn_by");

                    b.HasKey("Id")
                        .HasName("pk_lead_consents");

                    b.HasIndex("TenantId", "LeadId")
                        .HasDatabaseName("ix_lead_consents_tenant_id_lead_id");

                    b.HasIndex("TenantId", "LeadId", "Type")
                        .HasDatabaseName("ix_lead_consents_tenant_id_lead_id_type")
                        .HasFilter("status = 'Active'");

                    b.ToTable("lead_consents", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadMerge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<Guid>("MergedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_by");

                    b.Property<string>("OverriddenFields")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("overridden_fields");

                    b.Property<Guid>("SourceLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_lead_id");

                    b.Property<Guid>("TargetLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_lead_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_lead_merges");

                    b.HasIndex("TenantId", "SourceLeadId")
                        .HasDatabaseName("ix_lead_merges_tenant_id_source_lead_id");

                    b.HasIndex("TenantId", "TargetLeadId")
                        .HasDatabaseName("ix_lead_merges_tenant_id_target_lead_id");

                    b.ToTable("lead_merges", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadOwnerAssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssignmentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_method");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<Guid>("NewOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_owner_id");

                    b.Property<Guid?>("PreviousOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_owner_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_lead_owner_assignment_histories");

                    b.HasIndex("LeadId", "AssignedAt")
                        .HasDatabaseName("ix_lead_owner_assignment_histories_lead_id_assigned_at");

                    b.HasIndex("TenantId", "NewOwnerId")
                        .HasDatabaseName("ix_lead_owner_assignment_histories_tenant_id_new_owner_id");

                    b.ToTable("lead_owner_assignment_histories", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lead_reminders");

                    b.HasIndex("LeadId", "Status")
                        .HasDatabaseName("ix_lead_reminders_lead_id_status");

                    b.HasIndex("TenantId", "DueAt", "Status")
                        .HasDatabaseName("ix_lead_reminders_tenant_id_due_at_status");

                    b.ToTable("lead_reminders", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_lead_tags");

                    b.HasIndex("LeadId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_lead_tags_lead_id_tag");

                    b.HasIndex("TenantId", "Tag")
                        .HasDatabaseName("ix_lead_tags_tenant_id_tag");

                    b.ToTable("lead_tags", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.QualificationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HelpText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("label");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_value");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("PlaceholderText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("placeholder_text");

                    b.Property<string>("RulesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("rules_json");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_qualification_questions");

                    b.HasIndex("TemplateId", "Order")
                        .HasDatabaseName("ix_qualification_questions_template_id_order");

                    b.ToTable("qualification_questions", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.QualificationResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("AnsweredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("answered_by");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<int>("ComputedScore")
                        .HasColumnType("integer")
                        .HasColumnName("computed_score");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_qualification_responses");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_qualification_responses_lead_id");

                    b.HasIndex("TenantId", "LeadId")
                        .HasDatabaseName("ix_qualification_responses_tenant_id_lead_id");

                    b.HasIndex("TenantId", "TemplateId")
                        .HasDatabaseName("ix_qualification_responses_tenant_id_template_id");

                    b.ToTable("qualification_responses", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.QualificationSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_qualification_sections");

                    b.HasIndex("TemplateId", "Order")
                        .HasDatabaseName("ix_qualification_sections_template_id_order");

                    b.ToTable("qualification_sections", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.QualificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProductType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_type");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_qualification_templates");

                    b.HasIndex("TenantId", "ProductType")
                        .IsUnique()
                        .HasDatabaseName("ix_qualification_templates_tenant_id_product_type")
                        .HasFilter("product_type IS NOT NULL AND status = 'Published'");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_qualification_templates_tenant_id_status");

                    b.ToTable("qualification_templates", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.ScoreHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FactorsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("factors_json");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<Guid?>("QualificationResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("qualification_response_id");

                    b.Property<DateTimeOffset>("RecalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recalculated_at");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_event");

                    b.HasKey("Id")
                        .HasName("pk_score_histories");

                    b.HasIndex("QualificationResponseId")
                        .HasDatabaseName("ix_score_histories_qualification_response_id")
                        .HasFilter("qualification_response_id IS NOT NULL");

                    b.HasIndex("LeadId", "RecalculatedAt")
                        .HasDatabaseName("ix_score_histories_lead_id_recalculated_at");

                    b.ToTable("score_histories", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.TaskGenerationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionTemplate")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_template");

                    b.Property<TimeSpan>("DueDuration")
                        .HasColumnType("interval")
                        .HasColumnName("due_duration");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<TimeSpan>("SlaDuration")
                        .HasColumnType("interval")
                        .HasColumnName("sla_duration");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("task_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TitleTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_template");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_event_type");

                    b.HasKey("Id")
                        .HasName("pk_task_generation_rules");

                    b.HasIndex("TenantId", "TriggerEventType", "IsActive")
                        .HasDatabaseName("ix_task_generation_rules_tenant_id_trigger_event_type_is_active");

                    b.ToTable("task_generation_rules", "leads");
                });

            modelBuilder.Entity("Sankore.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_occurred_at");

                    b.ToTable("outbox_messages", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.CrmTask", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_crm_tasks_leads_lead_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.DispatchingRule", b =>
                {
                    b.OwnsOne("Sankore.Modules.Leads.Domain.ScoringWeights", "Weights", b1 =>
                        {
                            b1.Property<Guid>("DispatchingRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Agency")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_agency");

                            b1.Property<double>("Geography")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_geography");

                            b1.Property<double>("Language")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_language");

                            b1.Property<double>("Performance")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_performance");

                            b1.Property<double>("Product")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_product");

                            b1.Property<double>("Workload")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_workload");

                            b1.HasKey("DispatchingRuleId");

                            b1.ToTable("dispatching_rules", "leads");

                            b1.WithOwner()
                                .HasForeignKey("DispatchingRuleId")
                                .HasConstraintName("fk_dispatching_rules_dispatching_rules_id");
                        });

                    b.Navigation("Weights")
                        .IsRequired();
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.Lead", b =>
                {
                    b.OwnsOne("Sankore.Shared.Kernel.ValueObject.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lng");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId")
                                .HasConstraintName("fk_leads_leads_id");
                        });

                    b.OwnsOne("Sankore.Shared.Kernel.ValueObject.Money", "DesiredAmount", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("desired_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("desired_currency");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId")
                                .HasConstraintName("fk_leads_leads_id");
                        });

                    b.Navigation("DesiredAmount");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadActivity", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_activities_leads_lead_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadAssignment", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_assignments_leads_lead_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadOwnerAssignmentHistory", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_owner_assignment_histories_leads_lead_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadReminder", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_reminders_leads_lead_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadTag", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_tags_leads_lead_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.QualificationQuestion", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.QualificationTemplate", null)
                        .WithMany("Questions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualification_questions_qualification_templates_template_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.QualificationResponse", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualification_responses_leads_lead_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.QualificationSection", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.QualificationTemplate", null)
                        .WithMany("Sections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualification_sections_qualification_templates_template_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.ScoreHistory", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_histories_leads_lead_id");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.QualificationTemplate", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
