// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sankore.Modules.Leads.Infrastructure;

#nullable disable

namespace Sankore.Modules.Leads.Infrastructure.Migrations
{
    [DbContext(typeof(LeadsDbContext))]
    partial class LeadsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("leads")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.DispatchingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AntiMonopolyThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("anti_monopoly_threshold");

                    b.Property<TimeSpan>("FirstContactSla")
                        .HasColumnType("interval")
                        .HasColumnName("first_contact_sla");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxLeadsPerAgent")
                        .HasColumnType("integer")
                        .HasColumnName("max_leads_per_agent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_dispatching_rules");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_dispatching_rules_tenant_id_is_active");

                    b.ToTable("dispatching_rules", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentCollectedLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_collected_lead_id");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_address");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_email");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentAssignedId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_assigned_id");

                    b.Property<Guid?>("CurrentAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_assignment_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("InterestedProduct")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("interested_product");

                    b.Property<string>("LossReason")
                        .HasColumnType("text")
                        .HasColumnName("loss_reason");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("PreferredAgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_agency_id");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("preferred_language");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_leads_full_name");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_leads_phone_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_leads_tenant_id_status");

                    b.ToTable("leads", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<double>("CompatibilityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("compatibility_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FirstContactAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_contact_at");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text")
                        .HasColumnName("override_reason");

                    b.Property<DateTimeOffset>("SlaDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("strategy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("WasManualOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("was_manual_override");

                    b.HasKey("Id")
                        .HasName("pk_lead_assignments");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_lead_assignments_agent_id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_lead_assignments_lead_id");

                    b.HasIndex("SlaDeadline", "FirstContactAt")
                        .HasDatabaseName("ix_lead_assignments_sla_deadline_first_contact_at");

                    b.ToTable("lead_assignments", "leads");
                });

            modelBuilder.Entity("Sankore.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_occurred_at");

                    b.ToTable("outbox_messages", "leads");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.DispatchingRule", b =>
                {
                    b.OwnsOne("Sankore.Modules.Leads.Domain.ScoringWeights", "Weights", b1 =>
                        {
                            b1.Property<Guid>("DispatchingRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Geography")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_geography");

                            b1.Property<double>("Language")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_language");

                            b1.Property<double>("Performance")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_performance");

                            b1.Property<double>("Product")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_product");

                            b1.Property<double>("Workload")
                                .HasColumnType("double precision")
                                .HasColumnName("weight_workload");

                            b1.HasKey("DispatchingRuleId");

                            b1.ToTable("dispatching_rules", "leads");

                            b1.WithOwner()
                                .HasForeignKey("DispatchingRuleId")
                                .HasConstraintName("fk_dispatching_rules_dispatching_rules_id");
                        });

                    b.Navigation("Weights")
                        .IsRequired();
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.Lead", b =>
                {
                    b.OwnsOne("Sankore.Shared.Kernel.ValueObject.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lng");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId")
                                .HasConstraintName("fk_leads_leads_id");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Sankore.Modules.Leads.Domain.LeadAssignment", b =>
                {
                    b.HasOne("Sankore.Modules.Leads.Domain.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_assignments_leads_lead_id");
                });
#pragma warning restore 612, 618
        }
    }
}
