using MediatR;
using Microsoft.EntityFrameworkCore;
using Sankore.Modules.Workflow.Domain;
using Sankore.Modules.Workflow.Infrastructure;
using Sankore.Shared.Kernel;

namespace Sankore.Modules.Workflow.Features.Templates.Transitions.ListTransitions;

internal sealed class ListTransitionsHandler(WorkflowDbContext db)
    : IRequestHandler<ListTransitionsQuery, Result<List<TransitionDto>>>
{
    public async Task<Result<List<TransitionDto>>> Handle(ListTransitionsQuery request, CancellationToken ct)
    {
        var templateExists = await db.WorkflowTemplates
            .AnyAsync(t => t.Id == request.TemplateId, ct);

        if (!templateExists)
            return Result.Fail<List<TransitionDto>>($"Template {request.TemplateId} not found.");

        var transitions = await db.WorkflowTransitions
            .Where(t => t.TemplateId == request.TemplateId)
            .OrderBy(t => t.Priority)
            .ThenBy(t => t.EventCode)
            .Select(t => new TransitionDto(
                t.Id,
                t.FromStateId,
                t.ToStateId,
                t.EventCode,
                t.ToTerminalStatus,
                t.Priority,
                t.ConditionJson,
                t.IsAutoGenerated))
            .ToListAsync(ct);

        return Result.Ok(transitions);
    }
}
