using MediatR;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Sankore.Modules.Workflow.Domain;
using Sankore.Shared.Kernel;

namespace Sankore.Modules.Workflow.Features.Templates.Transitions.ListTransitions;

internal static class ListTransitionsEndpoint
{
    internal static IEndpointRouteBuilder MapListTransitions(this IEndpointRouteBuilder app)
    {
        app.MapGet("{templateId:guid}/transitions",
            async (Guid templateId, ISender sender, CancellationToken ct) =>
            {
                var result = await sender.Send(new ListTransitionsQuery(templateId), ct);
                return result.IsSuccess
                    ? Results.Ok(result.Value)
                    : Results.NotFound(new { error = result.Error });
            })
        .WithName("ListWorkflowTransitions")
        .WithSummary("List all transitions for a workflow template")
        .RequireAuthorization(Permissions.CanManageWorkflowSteps.Code)
        .Produces<List<TransitionDto>>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status404NotFound)
        .WithOpenApi();

        return app;
    }
}

internal sealed record TransitionDto(
    Guid Id,
    Guid FromStateId,
    Guid? ToStateId,
    string EventCode,
    WorkflowStatus? ToTerminalStatus,
    int Priority,
    string? ConditionJson,
    bool IsAutoGenerated);
