namespace Sankore.Modules.Leads.Domain;

using Sankore.Shared.Kernel;

/// <summary>
/// A unit of work generated by a business event (dispatch, score change, etc.)
/// or manually by a user. Ties together: type, priority, SLA, due date, and
/// the lead it relates to (US-M13-080).
/// </summary>
public sealed class CrmTask : ITenant
{
    public Guid Id { get; private set; }
    public Guid TenantId { get; private set; }
    public CrmTaskType Type { get; private set; }
    public CrmTaskPriority Priority { get; private set; }
    public string Title { get; private set; } = default!;
    public string? Description { get; private set; }
    public Guid? LeadId { get; private set; }
    public Guid? AssignedAgentId { get; private set; }
    public CrmTaskStatus Status { get; private set; }
    public DateTimeOffset DueAt { get; private set; }
    public DateTimeOffset? SlaDeadline { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset? StartedAt { get; private set; }
    public DateTimeOffset? CompletedAt { get; private set; }

    /// <summary>Simple name of the integration event that triggered this task; null for manual tasks.</summary>
    public string? TriggerEventType { get; private set; }
    public Guid? TriggerEventId { get; private set; }

    private CrmTask() { }

    public static CrmTask Create(
        Guid tenantId,
        CrmTaskType type,
        CrmTaskPriority priority,
        string title,
        DateTimeOffset dueAt,
        Guid? leadId = null,
        Guid? assignedAgentId = null,
        DateTimeOffset? slaDeadline = null,
        string? description = null,
        string? triggerEventType = null,
        Guid? triggerEventId = null)
        => new()
        {
            Id               = Guid.NewGuid(),
            TenantId         = tenantId,
            Type             = type,
            Priority         = priority,
            Title            = title,
            Description      = description,
            LeadId           = leadId,
            AssignedAgentId  = assignedAgentId,
            Status           = CrmTaskStatus.Pending,
            DueAt            = dueAt,
            SlaDeadline      = slaDeadline,
            CreatedAt        = DateTimeOffset.UtcNow,
            TriggerEventType = triggerEventType,
            TriggerEventId   = triggerEventId
        };

    public Result Complete()
    {
        if (Status == CrmTaskStatus.Cancelled)  return Result.Fail("TASK_CANCELLED");
        if (Status == CrmTaskStatus.Completed)  return Result.Fail("TASK_ALREADY_COMPLETED");
        Status      = CrmTaskStatus.Completed;
        CompletedAt = DateTimeOffset.UtcNow;
        return Result.Ok();
    }

    public Result Cancel()
    {
        if (Status == CrmTaskStatus.Completed) return Result.Fail("TASK_ALREADY_COMPLETED");
        if (Status == CrmTaskStatus.Cancelled) return Result.Fail("TASK_ALREADY_CANCELLED");
        Status = CrmTaskStatus.Cancelled;
        return Result.Ok();
    }

    public Result StartProgress()
    {
        if (Status != CrmTaskStatus.Pending) return Result.Fail("TASK_NOT_PENDING");
        Status    = CrmTaskStatus.InProgress;
        StartedAt = DateTimeOffset.UtcNow;
        return Result.Ok();
    }

    public void AssignTo(Guid agentId) => AssignedAgentId = agentId;
}
