// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sankore.Modules.Kyc.Infrastructure;

#nullable disable

namespace Sankore.Modules.Kyc.Infrastructure.Migrations
{
    [DbContext(typeof(KycDbContext))]
    [Migration("20261006223734_AddKycDocumentRegistry")]
    partial class AddKycDocumentRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kyc")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("decision");

                    b.Property<Guid>("KycFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_file_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("level");

                    b.Property<int>("LevelRank")
                        .HasColumnType("integer")
                        .HasColumnName("level_rank");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kyc_approval_steps");

                    b.HasIndex("KycFileId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ux_kyc_approval_steps_file_level");

                    b.HasIndex("KycFileId", "Decision", "LevelRank")
                        .HasDatabaseName("ix_kyc_approval_steps_pending_rank");

                    b.ToTable("kyc_approval_steps", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycConfidenceAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BreakdownJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FlagsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("flags_json");

                    b.Property<int>("GlobalScore")
                        .HasColumnType("integer")
                        .HasColumnName("global_score");

                    b.Property<Guid>("KycFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_file_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("ServiceVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_kyc_confidence_assessments");

                    b.HasIndex("KycFileId", "CreatedAt")
                        .HasDatabaseName("ix_kyc_confidence_assessments_file");

                    b.ToTable("kyc_confidence_assessments", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("KycFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_file_id");

                    b.Property<string>("RefusalReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("refusal_reason");

                    b.Property<string>("ReviewDecision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("review_decision");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_kyc_documents");

                    b.HasIndex("TenantId", "StorageRef")
                        .HasDatabaseName("ix_kyc_documents_storage_ref");

                    b.HasIndex("TenantId", "KycFileId", "Kind", "UploadedAt")
                        .HasDatabaseName("ix_kyc_documents_file_kind");

                    b.ToTable("kyc_documents", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycDocumentAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("KycFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_file_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kyc_document_access_logs");

                    b.HasIndex("TenantId", "ActorUserId", "AccessedAt")
                        .HasDatabaseName("ix_kyc_document_access_logs_actor");

                    b.HasIndex("TenantId", "KycFileId", "AccessedAt")
                        .HasDatabaseName("ix_kyc_document_access_logs_file");

                    b.ToTable("kyc_document_access_logs", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycFaceVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedFacePayload")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_face_payload");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("is_match");

                    b.Property<Guid>("KycFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_file_id");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("QualityScoresJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_scores_json");

                    b.Property<string>("SelfieStorageRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("selfie_storage_ref");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity_score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kyc_face_verifications");

                    b.HasIndex("KycFileId", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ux_kyc_face_verifications_file_attempt");

                    b.ToTable("kyc_face_verifications", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycFieldCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CorrectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_at");

                    b.Property<Guid>("CorrectedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("corrected_by");

                    b.Property<string>("EncryptedNewValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_new_value");

                    b.Property<string>("EncryptedPreviousValue")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_previous_value");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<Guid>("KycFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_file_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kyc_field_corrections");

                    b.HasIndex("KycFileId", "CorrectedAt")
                        .HasDatabaseName("ix_kyc_field_corrections_file");

                    b.ToTable("kyc_field_corrections", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("channel");

                    b.Property<string>("ConfidenceLevel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("confidence_level");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("DuplicateSuspected")
                        .HasColumnType("boolean")
                        .HasColumnName("duplicate_suspected");

                    b.Property<int>("FaceMatchAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("face_match_attempts");

                    b.Property<Guid?>("LastSubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_submitted_by");

                    b.Property<string>("ManualValidationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("manual_validation_reason");

                    b.Property<DateTimeOffset?>("ManuallyValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manually_validated_at");

                    b.Property<Guid?>("ManuallyValidatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("manually_validated_by");

                    b.Property<DateOnly?>("NextReviewDate")
                        .HasColumnType("date")
                        .HasColumnName("next_review_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VigilanceLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("vigilance_level");

                    b.HasKey("Id")
                        .HasName("pk_kyc_files");

                    b.HasIndex("TenantId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_kyc_files_open_per_customer")
                        .HasFilter("status NOT IN ('Rejected', 'Suspended')");

                    b.HasIndex("TenantId", "NextReviewDate")
                        .HasDatabaseName("ix_kyc_files_next_review");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_kyc_files_status");

                    b.HasIndex("TenantId", "AgencyId", "Status")
                        .HasDatabaseName("ix_kyc_files_agency_status");

                    b.ToTable("kyc_files", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycIdentityDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("doc_type");

                    b.Property<string>("EncryptedNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_number");

                    b.Property<string>("EncryptedOcrPayload")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_ocr_payload");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("IssuingCountry")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("issuing_country");

                    b.Property<Guid>("KycFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_file_id");

                    b.Property<string>("MrzDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("mrz_data_json");

                    b.Property<string>("NumberBlindIndex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("number_blind_index");

                    b.Property<string>("OcrFieldConfidencesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ocr_field_confidences_json");

                    b.Property<string>("OcrFieldsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ocr_fields_json");

                    b.Property<string>("ServiceVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_version");

                    b.Property<string>("StorageRef")
                        .HasColumnType("text")
                        .HasColumnName("storage_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_kyc_identity_documents");

                    b.HasIndex("KycFileId")
                        .HasDatabaseName("ix_kyc_identity_documents_file");

                    b.HasIndex("TenantId", "NumberBlindIndex")
                        .HasDatabaseName("ix_kyc_identity_documents_blind_index");

                    b.ToTable("kyc_identity_documents", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycReviewSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("KycFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("kyc_file_id");

                    b.Property<DateTimeOffset?>("MarkedDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_due_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_kyc_review_schedules");

                    b.HasIndex("KycFileId")
                        .HasDatabaseName("ix_kyc_review_schedules_file");

                    b.HasIndex("TenantId", "Status", "DueDate")
                        .HasDatabaseName("ix_kyc_review_schedules_due");

                    b.ToTable("kyc_review_schedules", "kyc");
                });

            modelBuilder.Entity("Sankore.Modules.Kyc.Domain.KycSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_kyc_settings");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_kyc_settings_tenant_key");

                    b.ToTable("kyc_settings", "kyc");
                });

            modelBuilder.Entity("Sankore.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_occurred_at");

                    b.ToTable("outbox_messages", "kyc");
                });
#pragma warning restore 612, 618
        }
    }
}
