// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sankore.Modules.Customers.Infrastructure;

#nullable disable

namespace Sankore.Modules.Customers.Infrastructure.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260929185134_AddClientImportJobs")]
    partial class AddClientImportJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.BeneficialOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("control_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EncryptedExternalDocumentNumber")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_external_document_number");

                    b.Property<DateOnly?>("ExternalDateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("external_date_of_birth");

                    b.Property<string>("ExternalDocumentBlindIndex")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_document_blind_index");

                    b.Property<string>("ExternalFullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("external_full_name");

                    b.Property<string>("ExternalNationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_nationality");

                    b.Property<Guid>("LegalClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_client_id");

                    b.Property<Guid?>("LinkedClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_client_id");

                    b.Property<decimal>("OwnershipPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ownership_percentage");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_beneficial_owners");

                    b.HasIndex("LinkedClientId")
                        .HasDatabaseName("ix_beneficial_owners_linked_client_id");

                    b.HasIndex("TenantId", "LegalClientId")
                        .HasDatabaseName("ix_beneficial_owners_tenant_id_legal_client_id");

                    b.HasIndex("TenantId", "LinkedClientId")
                        .HasDatabaseName("ix_beneficial_owners_tenant_id_linked_client_id");

                    b.ToTable("beneficial_owners", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdvisorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("advisor_user_id");

                    b.Property<string>("AgencyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agency_code");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("birth_place");

                    b.Property<string>("ClientNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("client_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DateOfBirthBlindIndex")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("date_of_birth_blind_index");

                    b.Property<string>("DeclaredIncomeCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("declared_income_currency");

                    b.Property<int>("DependentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("dependents_count");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Employer")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("employer");

                    b.Property<string>("EncryptedDateOfBirth")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_date_of_birth");

                    b.Property<string>("EncryptedDeclaredIncome")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_declared_income");

                    b.Property<string>("EncryptedIdentityDocumentNumber")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_identity_document_number");

                    b.Property<string>("EncryptedRegistrationNumber")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_registration_number");

                    b.Property<string>("EncryptedTaxIdNumber")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_tax_id_number");

                    b.Property<string>("FatherName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("father_name");

                    b.Property<string>("FirstName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("gender");

                    b.Property<DateOnly?>("IdentityDocumentExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("identity_document_expires_on");

                    b.Property<DateOnly?>("IdentityDocumentIssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("identity_document_issued_on");

                    b.Property<string>("IdentityDocumentNumberBlindIndex")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identity_document_number_blind_index");

                    b.Property<string>("IdentityDocumentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("identity_document_type");

                    b.Property<DateOnly?>("IncorporationDate")
                        .HasColumnType("date")
                        .HasColumnName("incorporation_date");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymized");

                    b.Property<string>("KycRejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("kyc_rejection_reason");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kyc_status");

                    b.Property<DateTimeOffset?>("KycUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_updated_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("LegalFormCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("legal_form_code");

                    b.Property<string>("LegalName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("legal_name");

                    b.Property<int?>("LoyaltyScore")
                        .HasColumnType("integer")
                        .HasColumnName("loyalty_score");

                    b.Property<DateTimeOffset?>("LoyaltyScoreAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loyalty_score_at");

                    b.Property<bool>("LoyaltyScoreProvisional")
                        .HasColumnType("boolean")
                        .HasColumnName("loyalty_score_provisional");

                    b.Property<string>("MaidenName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("maiden_name");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("marital_status");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_id");

                    b.Property<string>("MotherName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("mother_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("PhoneticKeyPrimary")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phonetic_key_primary");

                    b.Property<string>("PhoneticKeySecondary")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phonetic_key_secondary");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Profession")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("profession");

                    b.Property<string>("RegistrationNumberBlindIndex")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("registration_number_blind_index");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("risk_level");

                    b.Property<string>("SearchKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("search_key");

                    b.Property<DateTimeOffset?>("SegmentAssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("segment_assigned_at");

                    b.Property<string>("SegmentCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("segment_code");

                    b.Property<Guid?>("SourceLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("TenantId", "AdvisorUserId")
                        .HasDatabaseName("ix_clients_tenant_id_advisor_user_id");

                    b.HasIndex("TenantId", "AgencyId")
                        .HasDatabaseName("ix_clients_tenant_id_agency_id");

                    b.HasIndex("TenantId", "ClientNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_number");

                    b.HasIndex("TenantId", "DateOfBirthBlindIndex")
                        .HasDatabaseName("ix_clients_tenant_id_date_of_birth_blind_index");

                    b.HasIndex("TenantId", "DisplayName")
                        .HasDatabaseName("ix_clients_tenant_id_display_name");

                    b.HasIndex("TenantId", "FirstName")
                        .HasDatabaseName("ix_clients_tenant_id_first_name");

                    b.HasIndex("TenantId", "IdentityDocumentNumberBlindIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_identity_doc")
                        .HasFilter("identity_document_number_blind_index IS NOT NULL");

                    b.HasIndex("TenantId", "LastName")
                        .HasDatabaseName("ix_clients_tenant_id_last_name");

                    b.HasIndex("TenantId", "LegalName")
                        .HasDatabaseName("ix_clients_tenant_id_legal_name");

                    b.HasIndex("TenantId", "MergedIntoId")
                        .HasDatabaseName("ix_clients_tenant_id_merged_into_id");

                    b.HasIndex("TenantId", "PhoneticKeyPrimary")
                        .HasDatabaseName("ix_clients_tenant_id_phonetic_key_primary");

                    b.HasIndex("TenantId", "RegistrationNumberBlindIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_registration")
                        .HasFilter("registration_number_blind_index IS NOT NULL");

                    b.HasIndex("TenantId", "SearchKey")
                        .HasDatabaseName("ix_clients_tenant_id_search_key");

                    b.HasIndex("TenantId", "SegmentCode")
                        .HasDatabaseName("ix_clients_tenant_id_segment_code");

                    b.HasIndex("TenantId", "SourceLeadId")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_source_lead")
                        .HasFilter("source_lead_id IS NOT NULL");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_clients_tenant_id_status");

                    b.ToTable("clients", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientContactPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlindIndex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blind_index");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_value");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_client_contact_points");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_contact_points_client_id");

                    b.HasIndex("TenantId", "ClientId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_client_contact_points_primary")
                        .HasFilter("is_primary = true AND valid_to IS NULL");

                    b.HasIndex("TenantId", "Type", "BlindIndex")
                        .HasDatabaseName("ix_client_contact_points_tenant_id_type_blind_index");

                    b.ToTable("client_contact_points", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientExportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DownloadToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("download_token");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_reference");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters_json");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_client_export_jobs");

                    b.HasIndex("TenantId", "DownloadToken")
                        .IsUnique()
                        .HasDatabaseName("ux_client_export_jobs_token");

                    b.HasIndex("TenantId", "RequestedBy", "RequestedAt")
                        .HasDatabaseName("ix_client_export_jobs_tenant_id_requested_by_requested_at");

                    b.ToTable("client_export_jobs", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateOnly>("ConstitutionDate")
                        .HasColumnType("date")
                        .HasColumnName("constitution_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DissolutionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("dissolution_reason");

                    b.Property<DateTimeOffset?>("DissolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dissolved_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_client_groups");

                    b.HasIndex("TenantId", "AgencyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_client_groups_name");

                    b.ToTable("client_groups", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultAgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_agency_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<string>("FailureDetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("failure_details_json");

                    b.Property<Guid>("InitiatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("Skipped")
                        .HasColumnType("integer")
                        .HasColumnName("skipped");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Succeeded")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.HasKey("Id")
                        .HasName("pk_client_import_jobs");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_client_import_jobs_tenant_id_created_at");

                    b.HasIndex("TenantId", "InitiatedBy")
                        .HasDatabaseName("ix_client_import_jobs_tenant_id_initiated_by");

                    b.ToTable("client_import_jobs", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientLoyaltyScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown_json");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<bool>("IsProvisional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_provisional");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_client_loyalty_scores");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("ix_client_loyalty_scores_tenant_id_client_id");

                    b.HasIndex("TenantId", "ClientId", "ComputedAt")
                        .HasDatabaseName("ix_client_loyalty_scores_tenant_id_client_id_computed_at");

                    b.ToTable("client_loyalty_scores", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientMergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AbsorbedClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("absorbed_client_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_comment");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("FieldChoicesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_choices_json");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SurvivorClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("survivor_client_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_client_merge_requests");

                    b.HasIndex("AbsorbedClientId")
                        .HasDatabaseName("ix_client_merge_requests_absorbed_client_id");

                    b.HasIndex("SurvivorClientId")
                        .HasDatabaseName("ix_client_merge_requests_survivor_client_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_client_merge_requests_tenant_id_status");

                    b.HasIndex("TenantId", "WorkflowInstanceId")
                        .HasDatabaseName("ix_client_merge_requests_tenant_id_workflow_instance_id");

                    b.ToTable("client_merge_requests", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgencyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agency_code");

                    b.Property<int>("NextValue")
                        .HasColumnType("integer")
                        .HasColumnName("next_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_client_number_sequences");

                    b.HasIndex("TenantId", "AgencyCode", "Year")
                        .IsUnique()
                        .HasDatabaseName("ux_client_number_sequences");

                    b.ToTable("client_number_sequences", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EncryptedExternalDocumentNumber")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("encrypted_external_document_number");

                    b.Property<DateOnly?>("ExternalDateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("external_date_of_birth");

                    b.Property<string>("ExternalFullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("external_full_name");

                    b.Property<string>("ExternalPhoneBlindIndex")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_phone_blind_index");

                    b.Property<string>("ExternalPhoneEncrypted")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("external_phone_encrypted");

                    b.Property<Guid?>("ReciprocalRelationshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("reciprocal_relationship_id");

                    b.Property<Guid?>("RelatedClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_client_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_client_relationships");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_relationships_client_id");

                    b.HasIndex("RelatedClientId")
                        .HasDatabaseName("ix_client_relationships_related_client_id");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("ix_client_relationships_tenant_id_client_id");

                    b.HasIndex("TenantId", "RelatedClientId")
                        .HasDatabaseName("ix_client_relationships_tenant_id_related_client_id");

                    b.HasIndex("TenantId", "ClientId", "Type")
                        .HasDatabaseName("ix_client_relationships_tenant_id_client_id_type");

                    b.ToTable("client_relationships", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientSegmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("RuleCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("rule_code");

                    b.Property<string>("SegmentCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("segment_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_client_segment_history");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("ix_client_segment_history_tenant_id_client_id");

                    b.HasIndex("TenantId", "ClientId", "ValidFrom")
                        .HasDatabaseName("ix_client_segment_history_tenant_id_client_id_valid_from");

                    b.ToTable("client_segment_history", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("old_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_client_status_history");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_status_history_client_id");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("ix_client_status_history_tenant_id_client_id");

                    b.HasIndex("TenantId", "ClientId", "OccurredAt")
                        .HasDatabaseName("ix_client_status_history_tenant_id_client_id_occurred_at");

                    b.ToTable("client_status_history", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedup_key");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entry_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("reference_type");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_module");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_client_timeline_entries");

                    b.HasIndex("TenantId", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_client_timeline_dedup");

                    b.HasIndex("TenantId", "ClientId", "OccurredAt")
                        .HasDatabaseName("ix_client_timeline_entries_tenant_id_client_id_occurred_at");

                    b.ToTable("client_timeline_entries", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.CustomerSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_customer_settings");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_settings_key");

                    b.ToTable("customer_settings", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.DuplicateCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientAId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_a_id");

                    b.Property<Guid>("ClientBId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_b_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("FingerprintA")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_a");

                    b.Property<string>("FingerprintB")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_b");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons_json");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_duplicate_candidates");

                    b.HasIndex("ClientAId")
                        .HasDatabaseName("ix_duplicate_candidates_client_a_id");

                    b.HasIndex("ClientBId")
                        .HasDatabaseName("ix_duplicate_candidates_client_b_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_duplicate_candidates_tenant_id_status");

                    b.HasIndex("TenantId", "ClientAId", "ClientBId")
                        .IsUnique()
                        .HasDatabaseName("ux_duplicate_candidates_pair");

                    b.ToTable("duplicate_candidates", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("LeaveReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("leave_reason");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("OfficeRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("office_role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_group_memberships");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_group_memberships_client_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_memberships_group_id");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("ix_group_memberships_tenant_id_client_id");

                    b.HasIndex("TenantId", "GroupId")
                        .HasDatabaseName("ix_group_memberships_tenant_id_group_id");

                    b.HasIndex("TenantId", "GroupId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("ux_group_memberships_active")
                        .HasFilter("left_at IS NULL");

                    b.ToTable("group_memberships", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("TenantId", "ReceivedAt")
                        .HasDatabaseName("ix_inbox_messages_tenant_id_received_at");

                    b.ToTable("inbox_messages", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.LegalForm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_legal_forms");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_legal_forms_code");

                    b.ToTable("legal_forms", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.SensitiveDataAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("field_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sensitive_data_access_logs");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("ix_sensitive_data_access_logs_tenant_id_client_id");

                    b.HasIndex("TenantId", "ActorUserId", "AccessedAt")
                        .HasDatabaseName("ix_sensitive_data_access_logs_tenant_id_actor_user_id_accessed");

                    b.ToTable("sensitive_data_access_logs", "customers");
                });

            modelBuilder.Entity("Sankore.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_occurred_at");

                    b.ToTable("outbox_messages", "customers");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.BeneficialOwner", b =>
                {
                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("LinkedClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_beneficial_owners_clients_linked_client_id");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientContactPoint", b =>
                {
                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany("ContactPoints")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_contact_points_clients_client_id");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientMergeRequest", b =>
                {
                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("AbsorbedClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_merge_requests_clients_absorbed_client_id");

                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("SurvivorClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_merge_requests_clients_survivor_client_id");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientRelationship", b =>
                {
                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_relationships_clients_client_id");

                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("RelatedClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_client_relationships_clients_related_client_id");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientStatusHistory", b =>
                {
                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_status_history_clients_client_id");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.DuplicateCandidate", b =>
                {
                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_duplicate_candidates_clients_client_a_id");

                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_duplicate_candidates_clients_client_b_id");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.GroupMembership", b =>
                {
                    b.HasOne("Sankore.Modules.Customers.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_clients_client_id");

                    b.HasOne("Sankore.Modules.Customers.Domain.ClientGroup", null)
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_client_groups_group_id");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.Client", b =>
                {
                    b.Navigation("ContactPoints");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Sankore.Modules.Customers.Domain.ClientGroup", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
