<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>094ca550-509f-443b-8017-da4903e4068c</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\Bootstrapper\Sankore.Api\Sankore.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Docker" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" />
      <PackageReference Include="Aspire.Hosting.RabbitMQ" />
      <PackageReference Include="Aspire.Hosting.Seq" />
      <PackageReference Include="Aspire.Hosting.Redis" />
    </ItemGroup>

</Project>
