namespace Sankore.Api.Infrastructure;

using Microsoft.OpenApi;
using Microsoft.OpenApi.Extensions;
using Swashbuckle.AspNetCore.Swagger;

/// <summary>
/// Writes this API's OpenAPI document to a file and nothing else.
///
/// <para>
/// It exists because the front-end's generated client (<c>@sankore/crm-api</c>, from
/// <c>SankoreFront/swaggers/sankore-crm-api-swagger.json</c>) was regenerated by booting the whole
/// API and curling <c>/swagger/v1/swagger.json</c> — which needs a reachable PostgreSQL with every
/// module's migrations already applied, for a document that describes routes and schemas and reads
/// no row. A developer who could not boot could not regenerate, and a backend endpoint that exists
/// stays invisible to the front until somebody can.
/// </para>
/// </summary>
internal static class OpenApiEmitter
{
    private const string Flag = "--emit-openapi";

    /// <summary>The Swagger document name, as registered by <c>AddSwaggerGen</c>.</summary>
    private const string DocumentName = "v1";

    private const string DefaultOutputPath = "openapi.json";

    /// <summary>
    /// The output path when <c>--emit-openapi [path]</c> is present, otherwise <c>null</c> — which
    /// is what tells the host to run normally. The path is optional so the flag alone is usable.
    /// </summary>
    internal static string? OutputPathFrom(string[] args)
    {
        var index = Array.IndexOf(args, Flag);
        if (index < 0) return null;

        var next = index + 1 < args.Length ? args[index + 1] : null;

        // A following argument that is itself a flag is the next option, not this one's value.
        return string.IsNullOrWhiteSpace(next) || next.StartsWith('-')
            ? DefaultOutputPath
            : next;
    }

    internal static async Task WriteAsync(WebApplication app, string outputPath)
    {
        // STARTED, then stopped. Not optional: Swashbuckle builds the document from the API
        // explorer, which reads the endpoint data sources, and those are only materialised when the
        // host starts. Skipping this writes a syntactically valid document with ZERO paths — which
        // the front's generator accepts, producing a client with no methods at all.
        await app.StartAsync();

        try
        {
            // Resolved from the built host rather than re-created: the document must come from the
            // same SwaggerGen configuration the running API serves, enum-as-string converters
            // included.
            var swagger = app.Services.GetRequiredService<ISwaggerProvider>()
                .GetSwagger(DocumentName);

            if (swagger.Paths.Count == 0)
                throw new InvalidOperationException(
                    "The OpenAPI document came back with no paths. Something stopped the endpoints "
                    + "from being discovered; writing it would hand the client generator an empty "
                    + "API.");

            await SerializeAsync(swagger, outputPath, app.Logger);
        }
        finally
        {
            await app.StopAsync();
        }
    }

    private static async Task SerializeAsync(
        Microsoft.OpenApi.Models.OpenApiDocument swagger, string outputPath, ILogger logger)
    {

        var full = Path.GetFullPath(outputPath);
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);

        await using var stream = File.Create(full);
        await using var writer = new StreamWriter(stream);

        // 3.0, matching the document the front's generator already consumes. Writing 3.1 here would
        // change nullability representation across every generated model in one commit.
        swagger.SerializeAsV3(new Microsoft.OpenApi.Writers.OpenApiJsonWriter(writer));
        await writer.FlushAsync();

        logger.LogInformation(
            "OpenAPI document written to {OutputPath} ({PathCount} paths)", full, swagger.Paths.Count);
    }
}
