// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sankore.Admin.Infrastructure;

#nullable disable

namespace Sankore.Admin.Infrastructure.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260912205405_UpdateTenantTable")]
    partial class UpdateTenantTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sankore.Admin.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlockedReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("citext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaintenance")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RootUserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubscriptionState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TrialExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fqdn")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("RootUserEmail")
                        .IsUnique();

                    b.HasIndex("RootUserEmail", "Fqdn")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Sankore.Admin.Domain.TenantDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("citext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fqdn")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_domains_fqdn");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_domains_tenant_id");

                    b.HasIndex("TenantId", "IsPrimary")
                        .HasDatabaseName("ix_tenant_domains_tenant_primary");

                    b.ToTable("TenantDomains");
                });

            modelBuilder.Entity("Sankore.Admin.Domain.Tenant", b =>
                {
                    b.OwnsOne("Sankore.Admin.Domain.SubscriptionStateInfo", "SubscriptionStateInfo", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("NextRenewalAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("subscription_state_info_next_renewal_at");

                            b1.Property<string>("RenewalPeriod")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("subscription_state_info_renewal_period");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("SubscriptionStateInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
