namespace Sankore.Modules.Customers.Features.Groups.CreateGroup;

using MediatR;
using Sankore.Modules.Customers.Domain;
using Sankore.Shared.Infrastructure.Behaviors;
using Sankore.Shared.Kernel;
using Sankore.Shared.Kernel.Authorization;

/// <summary>
/// Creates a solidarity group, a tontine or a VSLA (US-M01-BE-19).
///
/// The group is born <see cref="GroupStatus.Forming"/>: it only becomes
/// <see cref="GroupStatus.Active"/> once it reaches its configured minimum size
/// AND has a President, a Treasurer and a Secretary — see
/// <c>ClientGroup.TryActivate</c>, triggered by the member and role slices.
///
/// This is the only Groups command whose target agency is part of the payload,
/// so it is the only one that delegates the perimeter check to
/// <c>AgencyAuthorizationBehavior</c> through <see cref="IAgencyScopedRequest"/>
/// (rejecting with <c>AGENCY_OUT_OF_SCOPE</c> before the handler runs).
/// </summary>
public sealed record CreateGroupCommand(
    GroupType Type,
    string Name,
    Guid AgencyId,
    DateOnly ConstitutionDate
) : IRequest<Result<CreateGroupResult>>, ICommand, IResourceCommand, IAgencyScopedRequest
{
    public string ResourceType => "ClientGroup";

    /// <summary>Null: the identifier is generated by the handler.</summary>
    public string? ResourceId => null;

    public Guid? TargetAgencyId => AgencyId;
}

public sealed record CreateGroupResult(Guid GroupId, string Name, string Type, string Status);
