namespace Sankore.Shared.Infrastructure.Tests.Spreadsheets;

using System.Globalization;
using ClosedXML.Excel;
using FluentAssertions;
using Sankore.Shared.Spreadsheets;
using Xunit;

/// <summary>
/// Runs under fr-FR on purpose: the defect this helper exists for is invisible on a machine
/// whose culture is invariant, which is most CI agents and no West-African server.
/// </summary>
public sealed class XlsxCellTests : IDisposable
{
    private readonly CultureInfo _original = CultureInfo.CurrentCulture;

    public XlsxCellTests()
    {
        var french = new CultureInfo("fr-FR");
        CultureInfo.CurrentCulture = french;
        CultureInfo.DefaultThreadCurrentCulture = french;
    }

    public void Dispose()
    {
        CultureInfo.CurrentCulture = _original;
        CultureInfo.DefaultThreadCurrentCulture = null;
    }

    private static IXLCell CellWith(Action<IXLCell> set)
    {
        var wb = new XLWorkbook();
        var cell = wb.AddWorksheet("s").Cell(1, 1);
        set(cell);
        return cell;
    }

    [Fact]
    public void A_decimal_keeps_its_dot()
    {
        var cell = CellWith(c => c.Value = 5.300489);

        XlsxCell.ReadAsText(cell).Should().Be("5.300489");
    }

    [Fact]
    public void A_negative_decimal_keeps_its_sign_and_dot()
    {
        var cell = CellWith(c => c.Value = -3.9678);

        XlsxCell.ReadAsText(cell).Should().Be("-3.9678");
    }

    [Fact]
    public void A_large_amount_does_not_become_scientific_notation()
    {
        // "G" would render 1.5E+06, which every parser here rejects.
        var cell = CellWith(c => c.Value = 1_500_000);

        XlsxCell.ReadAsText(cell).Should().Be("1500000");
    }

    [Fact]
    public void A_double_is_not_polluted_by_round_trip_digits()
    {
        // "R" gives 5.3004889999999996 on some values; the parsers would accept it, but the
        // number that lands in the database should be the one the operator typed.
        var cell = CellWith(c => c.Value = 5.300489);

        XlsxCell.ReadAsText(cell).Should().NotContain("999999");
    }

    [Fact]
    public void A_date_comes_back_iso_not_day_first()
    {
        // The silent one: "02/04/1987" read with the invariant short-date pattern is 4 February.
        var cell = CellWith(c => c.Value = new DateTime(1987, 4, 2));

        XlsxCell.ReadAsText(cell).Should().Be("1987-04-02");
    }

    [Fact]
    public void Text_is_returned_untouched_but_trimmed()
    {
        var cell = CellWith(c => c.Value = "  Crédit commerçant  ");

        XlsxCell.ReadAsText(cell).Should().Be("Crédit commerçant");
    }

    [Fact]
    public void Text_that_already_holds_an_invariant_number_is_left_alone()
    {
        // Files generated by a script carry text cells; they must keep working unchanged.
        var cell = CellWith(c => c.Value = "5.300489");

        XlsxCell.ReadAsText(cell).Should().Be("5.300489");
    }

    [Fact]
    public void An_empty_cell_is_empty_text_and_null_for_the_nullable_overload()
    {
        var cell = CellWith(_ => { });

        XlsxCell.ReadAsText(cell).Should().BeEmpty();
        XlsxCell.ReadAsTextOrNull(cell).Should().BeNull();
    }

    [Fact]
    public void A_whitespace_only_cell_reads_as_absent()
    {
        var cell = CellWith(c => c.Value = "   ");

        XlsxCell.ReadAsTextOrNull(cell).Should().BeNull();
    }

    [Fact]
    public void A_boolean_is_lower_cased_invariant()
    {
        var cell = CellWith(c => c.Value = true);

        XlsxCell.ReadAsText(cell).Should().Be("true");
    }
}
