using MediatR;
using Microsoft.EntityFrameworkCore;
using Sankore.Modules.Workflow.Infrastructure;
using Sankore.Shared.Kernel;

namespace Sankore.Modules.Workflow.Features.Templates.Transitions.RemoveTransition;

internal sealed class RemoveTransitionHandler(WorkflowDbContext db)
    : IRequestHandler<RemoveTransitionCommand, Result>
{
    public async Task<Result> Handle(RemoveTransitionCommand request, CancellationToken ct)
    {
        var template = await db.WorkflowTemplates
            .AsTracking()
            .Include(t => t.Steps)
            .FirstOrDefaultAsync(t => t.Id == request.TemplateId, ct);

        if (template is null)
            return Result.Fail($"Template {request.TemplateId} not found.");

        // Load the specific transition explicitly to avoid tracking issues.
        var transition = await db.WorkflowTransitions
            .FirstOrDefaultAsync(t => t.Id == request.TransitionId && t.TemplateId == request.TemplateId, ct);

        if (transition is null)
            return Result.Fail($"Transition {request.TransitionId} not found.");

        if (transition.IsAutoGenerated)
            return Result.Fail("Auto-generated transitions cannot be removed directly. Deactivate and re-activate the template to rebuild them.");

        try
        {
            template.RemoveTransition(request.TransitionId);
        }
        catch (DomainException ex)
        {
            return Result.Fail(ex.Message);
        }

        db.WorkflowTransitions.Remove(transition);
        await db.SaveChangesAsync(ct);
        return Result.Ok();
    }
}
