<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sankore.Modules.Integration.Adapters.Sab</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sankore.Modules.Integration\Sankore.Modules.Integration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sankore.Modules.Integration.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
