namespace Sankore.Modules.Leads.Tests.Features.Import;

using System.Globalization;
using ClosedXML.Excel;
using FluentAssertions;
using NSubstitute;
using Sankore.Modules.Leads.Domain;
using Sankore.Modules.Leads.Features.Import;
using Sankore.Modules.Leads.Features.Import.Readers;
using Sankore.Shared.Kernel;
using Xunit;

/// <summary>
/// A spreadsheet an agent fills in stores coordinates, amounts and dates as TYPED cells, not as
/// text. ClosedXML renders those with the server's culture while <see cref="LeadRowParser"/>
/// reads them back as invariant — so on a fr-FR host every numeric cell failed as "not a number",
/// and a date cell parsed silently to the wrong day. These tests run under fr-FR on purpose.
/// </summary>
public sealed class FileImportReaderCultureTests : IDisposable
{
    private readonly CultureInfo _original = CultureInfo.CurrentCulture;
    private readonly string _path = Path.Combine(
        Path.GetTempPath(), $"leads-{Guid.NewGuid():N}.xlsx");

    public FileImportReaderCultureTests()
    {
        // The culture that used to break the import.
        var french = new CultureInfo("fr-FR");
        CultureInfo.CurrentCulture = french;
        CultureInfo.DefaultThreadCurrentCulture = french;
    }

    public void Dispose()
    {
        CultureInfo.CurrentCulture = _original;
        CultureInfo.DefaultThreadCurrentCulture = null;
        if (File.Exists(_path)) File.Delete(_path);
    }

    /// <summary>Writes a one-row sheet whose cells are typed, the way Excel actually saves them.</summary>
    private void WriteWorkbook(Action<IXLWorksheet> fill)
    {
        using var wb = new XLWorkbook();
        var ws = wb.AddWorksheet("Leads");

        string[] headers =
        [
            "FullName", "PhoneNumber", "InterestedProduct", "Latitude", "Longitude",
            "DesiredAmount", "DesiredCurrency", "DateOfBirth", "Source",
        ];

        for (var i = 0; i < headers.Length; i++)
            ws.Cell(1, i + 1).Value = headers[i];

        ws.Cell(2, 1).Value = "Awa Ouattara";
        ws.Cell(2, 2).Value = "+2250708091801";
        ws.Cell(2, 3).Value = "Crédit commerçant";
        ws.Cell(2, 9).Value = "Agency";

        fill(ws);
        wb.SaveAs(_path);
    }

    private async Task<ImportLeadRow> ReadSingleRowAsync()
    {
        var store = Substitute.For<IFileStore>();
        store.ReadAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
            .Returns(_ => Task.FromResult<Stream>(File.OpenRead(_path)));

        var rows = await new FileImportReader(store).ReadAsync("f.xlsx", CancellationToken.None);
        return rows.Should().ContainSingle().Subject;
    }

    [Fact]
    public async Task Reads_numeric_coordinates_with_a_dot_whatever_the_server_culture()
    {
        WriteWorkbook(ws =>
        {
            ws.Cell(2, 4).Value = 5.300489;    // typed as a number, not a string
            ws.Cell(2, 5).Value = -3.967800;
        });

        var row = await ReadSingleRowAsync();

        row.Latitude.Should().Be("5.300489", "a comma makes the parser reject the row");
        row.Longitude.Should().Be("-3.9678");

        var parsed = LeadRowParser.Parse(row, new ImportDefaults(), LeadSource.FileImport);
        parsed.Errors.Should().BeEmpty();
        parsed.Row!.Latitude.Should().BeApproximately(5.300489, 1e-9);
        parsed.Row.Longitude.Should().BeApproximately(-3.9678, 1e-9);
    }

    [Fact]
    public async Task Reads_a_numeric_amount_without_scientific_notation_or_separators()
    {
        WriteWorkbook(ws =>
        {
            ws.Cell(2, 6).Value = 1_500_000;
            ws.Cell(2, 7).Value = "XOF";
        });

        var row = await ReadSingleRowAsync();

        row.DesiredAmount.Should().Be("1500000");

        var parsed = LeadRowParser.Parse(row, new ImportDefaults(), LeadSource.FileImport);
        parsed.Errors.Should().BeEmpty();
        parsed.Row!.DesiredAmount.Should().Be(1_500_000m);
    }

    [Fact]
    public async Task Reads_a_date_cell_as_the_day_it_actually_is()
    {
        // The dangerous one. Rendered in fr-FR the cell reads "02/04/1987" (or with a time part,
        // depending on its number format). Parsed as invariant — short date MM/dd/yyyy — that is
        // 4 February, not 2 April, and nothing reports it: the row imports with a wrong date.
        WriteWorkbook(ws => ws.Cell(2, 8).Value = new DateTime(1987, 4, 2));

        var row = await ReadSingleRowAsync();

        row.DateOfBirth.Should().Be("1987-04-02");

        var parsed = LeadRowParser.Parse(row, new ImportDefaults(), LeadSource.FileImport);
        parsed.Errors.Should().BeEmpty();
        parsed.Row!.DateOfBirth.Should().Be(new DateOnly(1987, 4, 2));
    }

    [Fact]
    public async Task Still_reads_values_stored_as_text()
    {
        // Files generated by a script carry text cells; they must keep working unchanged.
        WriteWorkbook(ws =>
        {
            ws.Cell(2, 4).Value = "5.300489";
            ws.Cell(2, 5).Value = "-3.9678";
            ws.Cell(2, 6).Value = "750000";
            ws.Cell(2, 7).Value = "XOF";
            ws.Cell(2, 8).Value = "1987-04-02";
        });

        var row = await ReadSingleRowAsync();

        row.Latitude.Should().Be("5.300489");
        row.DesiredAmount.Should().Be("750000");
        row.DateOfBirth.Should().Be("1987-04-02");

        LeadRowParser.Parse(row, new ImportDefaults(), LeadSource.FileImport)
            .Errors.Should().BeEmpty();
    }

    [Fact]
    public async Task An_empty_typed_cell_stays_null()
    {
        WriteWorkbook(_ => { });

        var row = await ReadSingleRowAsync();

        row.Latitude.Should().BeNull();
        row.DesiredAmount.Should().BeNull();
        row.DateOfBirth.Should().BeNull();

        // Blank coordinates mean "unknown", which the parser turns into 0/0 without complaining.
        var parsed = LeadRowParser.Parse(row, new ImportDefaults(), LeadSource.FileImport);
        parsed.Errors.Should().BeEmpty();
        parsed.Row!.Latitude.Should().Be(0);
    }
}
