// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sankore.Modules.Administration.Infrastructure;

#nullable disable

namespace Sankore.Modules.Administration.Infrastructure.Migrations
{
    [DbContext(typeof(AdministrationDbContext))]
    [Migration("20260905161137_AddNullableProfileAddress")]
    partial class AddNullableProfileAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("administration")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", "administration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", "administration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", "administration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", "administration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgencyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentAgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_agency_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TerritoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("territory_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.HasIndex("ParentAgencyId")
                        .HasDatabaseName("ix_agencies_parent_agency_id");

                    b.HasIndex("TerritoryId")
                        .HasDatabaseName("ix_agencies_territory_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_agencies_tenant_id_code");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("ix_agencies_tenant_id_is_deleted");

                    b.HasIndex("TenantId", "ParentAgencyId")
                        .HasDatabaseName("ix_agencies_tenant_id_parent_agency_id");

                    b.ToTable("agencies", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<bool>("IsAssignable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_assignable");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_system");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_app_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("app_roles", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<int>("ActiveLeadsCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_leads_count");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<double>("ConversionRate30D")
                        .HasColumnType("double precision")
                        .HasColumnName("conversion_rate30d");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_notifications");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<int>("HotLeadsCount")
                        .HasColumnType("integer")
                        .HasColumnName("hot_leads_count");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_user");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<DateTimeOffset>("PasswordExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_expires_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<Guid>("ReportToId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_to_id");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.PrimitiveCollection<List<string>>("Specialties")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("specialties");

                    b.PrimitiveCollection<List<string>>("SpokenLanguages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("spoken_languages");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_app_users_agency_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId", "AgencyId")
                        .HasDatabaseName("ix_app_users_tenant_id_agency_id");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_tenant_id_normalized_email");

                    b.ToTable("app_users", "administration", t =>
                        {
                            t.HasCheckConstraint("CK_User_AgencyId_RequiredForStandard", "(\"AccountType\" != 'Standard') OR (\"AgencyId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_User_System_NoAgency", "(\"AccountType\" != 'System') OR (\"AgencyId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<DateTime>("SetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_histories");

                    b.HasIndex("UserId", "SetAt")
                        .HasDatabaseName("ix_password_histories_user_id_set_at");

                    b.ToTable("password_histories", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.PermissionAttribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope_type");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_permission_attributions");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_permission_attributions_tenant_id_user_id");

                    b.HasIndex("UserId", "PermissionCode", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_attributions_user_id_permission_code_scope_id")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("permission_attributions", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.ProductSpeciality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_product_specialities");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_product_specialities_tenant_id_code");

                    b.ToTable("product_specialities", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_permissions_role_id_permission_id");

                    b.ToTable("role_permissions", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.TenantNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialVaultPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("credential_vault_path");

                    b.Property<DateTimeOffset?>("CurrentMonthStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_month_started_at");

                    b.Property<int>("CurrentMonthUsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_month_usage_count");

                    b.Property<string>("FromEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("from_email");

                    b.Property<string>("FromName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_name");

                    b.Property<int?>("MonthlyQuotaLimit")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_quota_limit");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider_type");

                    b.Property<string>("ReplyToEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reply_to_email");

                    b.Property<string>("SendingDomain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("sending_domain");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<bool>("UseDefaultPlatformProvider")
                        .HasColumnType("boolean")
                        .HasColumnName("use_default_platform_provider");

                    b.HasKey("Id")
                        .HasName("pk_tenant_notification_settings");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_notification_settings_tenant_id");

                    b.ToTable("tenant_notification_settings", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.Territory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("ProductSpecialities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("product_specialities");

                    b.Property<double>("RayonKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("rayon_km");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_territories");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_territories_tenant_id_code");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_territories_tenant_id_is_active");

                    b.ToTable("territories", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.UserLoginLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occured_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_login_locations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_locations_user_id");

                    b.ToTable("user_login_locations", "administration");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uuid")
                        .HasColumnName("additional_email");

                    b.Property<string>("AdditionalEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("additional_email");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_language");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_profile");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profile_user_id");

                    b.ToTable("user_profile", "administration", t =>
                        {
                            t.Property("AdditionalEmail")
                                .HasColumnName("additional_email1");
                        });
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("user_roles", "administration");
                });

            modelBuilder.Entity("Sankore.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_occurred_at");

                    b.ToTable("outbox_messages", "administration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.Agency", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.Agency", null)
                        .WithMany()
                        .HasForeignKey("ParentAgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_agencies_agencies_parent_agency_id");

                    b.HasOne("Sankore.Modules.Administration.Domain.Territory", null)
                        .WithMany("Agencies")
                        .HasForeignKey("TerritoryId")
                        .HasConstraintName("fk_agencies_territories_territory_id");

                    b.OwnsOne("Sankore.Shared.Kernel.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AgencyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_zipcode");

                            b1.HasKey("AgencyId");

                            b1.ToTable("agencies", "administration");

                            b1.WithOwner()
                                .HasForeignKey("AgencyId")
                                .HasConstraintName("fk_agencies_agencies_id");

                            b1.OwnsOne("Sankore.Shared.Kernel.ValueObject.GeoPoint", "Location", b2 =>
                                {
                                    b2.Property<Guid>("AddressAgencyId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("address_location_lat");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("address_location_lng");

                                    b2.HasKey("AddressAgencyId");

                                    b2.ToTable("agencies", "administration");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressAgencyId")
                                        .HasConstraintName("fk_agencies_agencies_id");
                                });

                            b1.Navigation("Location");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.AppUser", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.Agency", "Agency")
                        .WithMany("Users")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_users_agencies_agency_id");

                    b.OwnsOne("Sankore.Shared.Kernel.ValueObject.GeoPoint", "LastKnownLocation", b1 =>
                        {
                            b1.Property<Guid>("AppUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lng");

                            b1.HasKey("AppUserId");

                            b1.ToTable("app_users", "administration");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId")
                                .HasConstraintName("fk_app_users_app_users_id");
                        });

                    b.Navigation("Agency");

                    b.Navigation("LastKnownLocation");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.PasswordHistory", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_histories_app_users_user_id");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.PermissionAttribution", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", "User")
                        .WithMany("PermissionAttributions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permission_attributions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.RolePermission", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Sankore.Modules.Administration.Domain.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.Territory", b =>
                {
                    b.OwnsOne("Sankore.Shared.Kernel.ValueObject.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("TerritoryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_lng");

                            b1.HasKey("TerritoryId");

                            b1.ToTable("territories", "administration");

                            b1.WithOwner()
                                .HasForeignKey("TerritoryId")
                                .HasConstraintName("fk_territories_territories_id");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.UserLoginLocation", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_login_locations_app_users_user_id");

                    b.OwnsOne("Sankore.Shared.Kernel.ValueObject.GeoPoint", "Location", b1 =>
                        {
                            b1.Property<Guid>("UserLoginLocationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lng");

                            b1.HasKey("UserLoginLocationId");

                            b1.ToTable("user_login_locations", "administration");

                            b1.WithOwner()
                                .HasForeignKey("UserLoginLocationId")
                                .HasConstraintName("fk_user_login_locations_user_login_locations_id");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.UserProfile", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Sankore.Modules.Administration.Domain.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profile_app_users_user_id");

                    b.OwnsOne("Sankore.Shared.Kernel.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("additional_email");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .HasColumnType("text")
                                .HasColumnName("address_country");

                            b1.Property<string>("State")
                                .HasColumnType("text")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("text")
                                .HasColumnName("address_zipcode");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profile", "administration");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId")
                                .HasConstraintName("fk_user_profile_user_profile_additional_email");

                            b1.OwnsOne("Sankore.Shared.Kernel.ValueObject.GeoPoint", "Location", b2 =>
                                {
                                    b2.Property<Guid>("AddressUserProfileId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("additional_email");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("address_location_lat");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("address_location_lng");

                                    b2.HasKey("AddressUserProfileId");

                                    b2.ToTable("user_profile", "administration");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressUserProfileId")
                                        .HasConstraintName("fk_user_profile_user_profile_additional_email");
                                });

                            b1.Navigation("Location");
                        });

                    b.OwnsOne("Sankore.Shared.Kernel.PhoneNumber", "HomeNumber", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("additional_email");

                            b1.Property<DateTimeOffset?>("ConfirmedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("home_number_confirmed_at");

                            b1.Property<string>("Contact")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("home_number_contact");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("home_number_is_primary");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profile", "administration");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId")
                                .HasConstraintName("fk_user_profile_user_profile_additional_email");
                        });

                    b.OwnsOne("Sankore.Shared.Kernel.PhoneNumber", "PersonalNumber", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("additional_email");

                            b1.Property<DateTimeOffset?>("ConfirmedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("personal_number_confirmed_at");

                            b1.Property<string>("Contact")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("personal_number_contact");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("personal_number_is_primary");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profile", "administration");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId")
                                .HasConstraintName("fk_user_profile_user_profile_additional_email");
                        });

                    b.OwnsOne("Sankore.Shared.Kernel.PhoneNumber", "WorkNumber", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("additional_email");

                            b1.Property<DateTimeOffset?>("ConfirmedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("work_number_confirmed_at");

                            b1.Property<string>("Contact")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("work_number_contact");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("work_number_is_primary");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profile", "administration");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId")
                                .HasConstraintName("fk_user_profile_user_profile_additional_email");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("HomeNumber")
                        .IsRequired();

                    b.Navigation("PersonalNumber")
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.UserRole", b =>
                {
                    b.HasOne("Sankore.Modules.Administration.Domain.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Sankore.Modules.Administration.Domain.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.Agency", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.AppUser", b =>
                {
                    b.Navigation("PermissionAttributions");

                    b.Navigation("Profile");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Sankore.Modules.Administration.Domain.Territory", b =>
                {
                    b.Navigation("Agencies");
                });
#pragma warning restore 612, 618
        }
    }
}
