namespace Sankore.Modules.Workflow.Domain;

/// <summary>
/// Defines a valid state transition in the workflow state machine.
/// When a <see cref="WorkflowInstance"/> fires <see cref="EventCode"/> while on a step
/// matching <see cref="FromStateId"/>, it moves to <see cref="ToStateId"/>
/// or terminates with <see cref="ToTerminalStatus"/> when <see cref="ToStateId"/> is null.
/// </summary>
public sealed class WorkflowTransition
{
    public Guid Id { get; private set; }
    public Guid TemplateId { get; private set; }

    /// <summary>The step definition that acts as the source state.</summary>
    public Guid FromStateId { get; private set; }

    /// <summary>Target step definition Id. Null when the transition ends the workflow.</summary>
    public Guid? ToStateId { get; private set; }

    /// <summary>
    /// Terminal <see cref="WorkflowStatus"/> to apply when <see cref="ToStateId"/> is null.
    /// </summary>
    public WorkflowStatus? ToTerminalStatus { get; private set; }

    /// <summary>Event code that triggers this transition (see <see cref="EventCodes"/>).</summary>
    public string EventCode { get; private set; } = string.Empty;

    /// <summary>Lower value wins when multiple transitions match the same event from the same state.</summary>
    public int Priority { get; private set; }

    /// <summary>
    /// Optional JSON-serialised <see cref="WorkflowCondition"/> expression tree.
    /// When null the transition fires unconditionally.
    /// </summary>
    public string? ConditionJson { get; private set; }

    /// <summary>
    /// True for transitions generated automatically by <see cref="WorkflowTemplate.Activate"/>.
    /// False for transitions added manually via <see cref="WorkflowTemplate.AddTransition"/>.
    /// Allows re-activation to rebuild only the auto-generated transitions without
    /// touching hand-crafted conditional routes.
    /// </summary>
    public bool IsAutoGenerated { get; private set; }

    private WorkflowTransition() { }

    internal static WorkflowTransition Create(
        Guid templateId,
        Guid fromStateId,
        Guid? toStateId,
        string eventCode,
        WorkflowStatus? toTerminalStatus = null,
        string? conditionJson = null,
        int priority = 0,
        bool isAutoGenerated = false) =>
        new()
        {
            Id               = Guid.NewGuid(),
            TemplateId       = templateId,
            FromStateId      = fromStateId,
            ToStateId        = toStateId,
            ToTerminalStatus = toTerminalStatus,
            EventCode        = eventCode,
            ConditionJson    = conditionJson,
            Priority         = priority,
            IsAutoGenerated  = isAutoGenerated
        };
}
