using Sankore.Modules.Workflow.Domain.Events;
using Sankore.Shared.Kernel;

namespace Sankore.Modules.Workflow.Domain;

/// <summary>
/// Defines the approval circuit for a given entity type within a tenant.
/// A tenant can have at most one active template per EntityType.
/// </summary>
public sealed class WorkflowTemplate : AggregateRoot
{
    public Guid Id { get; private set; }

    /// <summary>Entity type this template applies to (e.g. "Lead", "Opportunity").</summary>
    public string EntityType { get; private set; } = string.Empty;

    public string Name { get; private set; } = string.Empty;
    public string? Description { get; private set; }
    public bool IsActive { get; private set; }

    /// <summary>
    /// Monotonically increasing version number. Version 1 = original template.
    /// New versions are created via <see cref="CreateDraft"/> without touching the active one.
    /// </summary>
    public int Version { get; private set; } = 1;

    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }
    public Guid CreatedByUserId { get; private set; }

    private readonly List<WorkflowStepDefinition> _steps = [];
    public IReadOnlyCollection<WorkflowStepDefinition> Steps => _steps.AsReadOnly();

    private readonly List<WorkflowTransition> _transitions = [];
    public IReadOnlyCollection<WorkflowTransition> Transitions => _transitions.AsReadOnly();

    private WorkflowTemplate() { }

    public static WorkflowTemplate Create(
        Guid tenantId,
        string entityType,
        string name,
        Guid createdByUserId,
        string? description = null)
    {
        if (string.IsNullOrWhiteSpace(entityType))
            throw new DomainException("EntityType is required.");
        if (string.IsNullOrWhiteSpace(name))
            throw new DomainException("Template name is required.");

        var now = DateTimeOffset.UtcNow;
        return new WorkflowTemplate
        {
            Id = Guid.NewGuid(),
            TenantId = tenantId,
            EntityType = entityType.Trim(),
            Name = name.Trim(),
            Description = description?.Trim(),
            IsActive = false,
            Version = 1,
            CreatedAt = now,
            UpdatedAt = now,
            CreatedByUserId = createdByUserId
        };
    }

    public void Update(string name, string? description)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new DomainException("Template name is required.");

        Name = name.Trim();
        Description = description?.Trim();
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void Activate()
    {
        if (_steps.Count == 0)
            throw new DomainException("Cannot activate a template with no steps.");

        // Rebuild transitions from the current step arrangement.
        _transitions.Clear();
        var sorted = _steps.OrderBy(s => s.Order).ToList();
        for (var i = 0; i < sorted.Count; i++)
        {
            var cur    = sorted[i];
            bool isLast = i == sorted.Count - 1;

            // APPROVE → advance to next step, or complete the workflow.
            // Priority 100 makes these the fallback; custom conditional transitions
            // added via AddTransition() at lower priority values take precedence.
            _transitions.Add(WorkflowTransition.Create(
                Id, cur.Id,
                toStateId:        isLast ? null : sorted[i + 1].Id,
                EventCodes.Approve,
                toTerminalStatus: isLast ? WorkflowStatus.Completed : null,
                priority:         100,
                isAutoGenerated:  true));

            // REJECT → rejected terminal (applies at any step)
            _transitions.Add(WorkflowTransition.Create(
                Id, cur.Id, toStateId: null,
                EventCodes.Reject,
                toTerminalStatus: WorkflowStatus.Rejected,
                priority:         100,
                isAutoGenerated:  true));
        }

        IsActive = true;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void Deactivate()
    {
        IsActive = false;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public WorkflowStepDefinition AddStep(
        int order,
        string name,
        string? description = null,
        string? approverRoleCode = null,
        int? timeoutHours = null)
    {
        if (_steps.Any(s => s.Order == order))
            throw new DomainException($"A step with order {order} already exists.");

        var step = WorkflowStepDefinition.Create(Id, order, name, description, approverRoleCode, timeoutHours);
        _steps.Add(step);
        UpdatedAt = DateTimeOffset.UtcNow;
        return step;
    }

    /// <summary>
    /// Adds a custom (non-auto-generated) transition to this template.
    /// Custom transitions default to priority 0, which is lower than the auto-generated
    /// fallbacks (priority 100), so they are evaluated first.
    /// Use <paramref name="conditionJson"/> to limit when the transition fires.
    /// </summary>
    public WorkflowTransition AddTransition(
        Guid fromStateId,
        Guid? toStateId,
        string eventCode,
        WorkflowStatus? toTerminalStatus = null,
        string? conditionJson = null,
        int priority = 0)
    {
        if (_steps.All(s => s.Id != fromStateId))
            throw new DomainException("FromState step not found in this template.");
        if (toStateId.HasValue && _steps.All(s => s.Id != toStateId.Value))
            throw new DomainException("ToState step not found in this template.");
        if (string.IsNullOrWhiteSpace(eventCode))
            throw new DomainException("EventCode is required.");

        var transition = WorkflowTransition.Create(
            Id, fromStateId, toStateId, eventCode,
            toTerminalStatus, conditionJson, priority, isAutoGenerated: false);
        _transitions.Add(transition);
        UpdatedAt = DateTimeOffset.UtcNow;
        return transition;
    }

    /// <summary>Removes a custom transition. Auto-generated transitions cannot be removed directly.</summary>
    public void RemoveTransition(Guid transitionId)
    {
        var transition = _transitions.FirstOrDefault(t => t.Id == transitionId)
            ?? throw new DomainException("Transition not found.");
        if (transition.IsAutoGenerated)
            throw new DomainException(
                "Auto-generated transitions cannot be removed directly. " +
                "Deactivate and re-activate the template to rebuild them.");
        _transitions.Remove(transition);
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Creates a new inactive draft of this template at <see cref="Version"/> + 1,
    /// cloning all steps, their rules, and custom (non-auto-generated) transitions.
    /// The caller is responsible for persisting the returned template and all its children.
    /// Auto-generated transitions are NOT cloned — they will be rebuilt when the draft is activated.
    /// </summary>
    public WorkflowTemplate CreateDraft(Guid createdByUserId)
    {
        var now = DateTimeOffset.UtcNow;
        var draft = new WorkflowTemplate
        {
            Id              = Guid.NewGuid(),
            TenantId        = TenantId,
            EntityType      = EntityType,
            Name            = Name,
            Description     = Description,
            IsActive        = false,
            Version         = Version + 1,
            CreatedAt       = now,
            UpdatedAt       = now,
            CreatedByUserId = createdByUserId
        };

        // Clone steps, building old→new Id map for transition remapping.
        var stepIdMap = new Dictionary<Guid, Guid>();
        foreach (var step in _steps.OrderBy(s => s.Order))
        {
            var newStep = WorkflowStepDefinition.Create(
                draft.Id, step.Order, step.Name, step.Description,
                step.ApproverRoleCode, step.TimeoutHours);

            stepIdMap[step.Id] = newStep.Id;

            foreach (var rule in step.Rules)
                newStep.AddRule(rule.RuleType, rule.Field, rule.Operator, rule.Value, rule.LogicalGroup);

            draft._steps.Add(newStep);
        }

        // Clone custom transitions only — auto-generated are rebuilt on Activate().
        foreach (var t in _transitions.Where(t => !t.IsAutoGenerated))
        {
            if (!stepIdMap.TryGetValue(t.FromStateId, out var newFrom))
                continue;

            Guid? newTo = t.ToStateId.HasValue && stepIdMap.TryGetValue(t.ToStateId.Value, out var mapped)
                ? mapped : null;

            draft._transitions.Add(WorkflowTransition.Create(
                draft.Id, newFrom, newTo, t.EventCode,
                t.ToTerminalStatus, t.ConditionJson, t.Priority, isAutoGenerated: false));
        }

        return draft;
    }

    public void RemoveStep(Guid stepId)
    {
        var step = _steps.FirstOrDefault(s => s.Id == stepId)
            ?? throw new DomainException("Step not found.");
        _steps.Remove(step);
        // Remove all transitions referencing the deleted step
        _transitions.RemoveAll(t => t.FromStateId == stepId || t.ToStateId == stepId);
        UpdatedAt = DateTimeOffset.UtcNow;
    }
}
