using MediatR;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Sankore.Shared.Kernel;

namespace Sankore.Modules.Workflow.Features.Templates.GetTemplateDiff;

internal static class GetTemplateDiffEndpoint
{
    public static IEndpointRouteBuilder MapGetTemplateDiff(this IEndpointRouteBuilder app)
    {
        app.MapGet("{id:guid}/diff", async (
            Guid id,
            Guid compareWith,
            ISender sender,
            CancellationToken ct) =>
        {
            var result = await sender.Send(new GetTemplateDiffQuery(id, compareWith), ct);
            return result.IsSuccess
                ? Results.Ok(result.Value)
                : Results.BadRequest(new { error = result.Error });
        })
        .WithName("GetTemplateDiff")
        .WithSummary("Diff two workflow template versions. Steps matched by Order; transitions matched by EventCode + source/target step order.")
        .RequireAuthorization(Permissions.CanReadWorkflow.Code)
        .Produces<TemplateDiffDto>()
        .Produces<object>(StatusCodes.Status400BadRequest)
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .WithOpenApi();

        return app;
    }
}

// ─── DTOs ──────────────────────────────────────────────────────────────────

public sealed record TemplateDiffDto(
    Guid FromTemplateId,
    int FromVersion,
    Guid ToTemplateId,
    int ToVersion,
    string EntityType,
    StepsDiffDto Steps,
    TransitionsDiffDto Transitions);

public sealed record StepsDiffDto(
    IReadOnlyList<StepSnapshotDto> Added,
    IReadOnlyList<StepSnapshotDto> Removed,
    IReadOnlyList<StepChangedDto> Changed);

public sealed record StepSnapshotDto(
    int Order,
    string Code,
    string Name,
    string? Description,
    string? ApproverRoleCode,
    int? TimeoutHours);

public sealed record StepChangedDto(
    int Order,
    string Code,
    Dictionary<string, FieldChangedDto> Changes);

public sealed record TransitionsDiffDto(
    IReadOnlyList<TransitionSnapshotDto> Added,
    IReadOnlyList<TransitionSnapshotDto> Removed,
    IReadOnlyList<TransitionChangedDto> Changed);

public sealed record TransitionSnapshotDto(
    int? FromStepOrder,
    int? ToStepOrder,
    string? ToTerminalStatus,
    string EventCode,
    int Priority,
    string? ConditionJson,
    bool IsAutoGenerated);

public sealed record TransitionChangedDto(
    string Key,
    Dictionary<string, FieldChangedDto> Changes);

public sealed record FieldChangedDto(string? From, string? To);
