// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sankore.Modules.Integration.Infrastructure;

#nullable disable

namespace Sankore.Modules.Integration.Infrastructure.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    partial class IntegrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("integration")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.CbsSnapshot", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("CrmCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("crm_customer_id");

                    b.Property<string>("AccountsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("accounts");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("KycLevelInCbs")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kyc_level_in_cbs");

                    b.Property<string>("LoansJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("loans");

                    b.Property<decimal>("MonthlyFlow")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_flow");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<decimal>("TotalBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_balance");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TenantId", "CrmCustomerId")
                        .HasName("pk_cbs_customer_snapshot");

                    b.HasIndex("TenantId", "SnapshotAt")
                        .HasDatabaseName("ix_cbs_customer_snapshot_tenant_snapshot_at");

                    b.ToTable("cbs_customer_snapshot", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationBatchFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AckReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ack_received_at");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<string>("FailureDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_detail");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_integration_batch_file");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_integration_batch_file_tenant_status");

                    b.HasIndex("TenantId", "ConnectionId", "Direction", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_batch_file_sequence");

                    b.ToTable("integration_batch_file", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorFamily")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("error_family");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("operation");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id", "At")
                        .HasName("pk_integration_call_log");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_integration_call_log_command")
                        .HasFilter("command_id IS NOT NULL");

                    b.HasIndex("TenantId", "At")
                        .HasDatabaseName("ix_integration_call_log_tenant_at");

                    b.ToTable("integration_call_log", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid?>("BatchFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_file_id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("command_type");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CrmId")
                        .HasColumnType("uuid")
                        .HasColumnName("crm_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ExternalResponseRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_response_ref");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastErrorFamily")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("last_error_family");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("PayloadEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("payload_encrypted");

                    b.Property<string>("PayloadFieldNames")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("payload_field_names");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_integration_command");

                    b.HasIndex("BatchFileId")
                        .HasDatabaseName("ix_integration_command_batch_file")
                        .HasFilter("batch_file_id IS NOT NULL");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_integration_command_status_next_attempt");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_command_tenant_idempotency");

                    b.HasIndex("TenantId", "EntityType", "CrmId", "CreatedAt")
                        .HasDatabaseName("ix_integration_command_tenant_entity_created");

                    b.ToTable("integration_command", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("family");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastHealthAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_health_at");

                    b.Property<string>("LastHealthDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_health_detail");

                    b.Property<bool?>("LastHealthStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("last_health_status");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RelayAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("relay_agent_id");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_integration_connection");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_connection_active_core_banking")
                        .HasFilter("is_active AND family = 'CoreBanking'");

                    b.HasIndex("TenantId", "Family", "IsActive")
                        .HasDatabaseName("ix_integration_connection_tenant_family_active");

                    b.ToTable("integration_connection", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CrmCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crm_code");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("domain");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_code");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_integration_mapping");

                    b.HasIndex("TenantId", "ConnectionId", "Domain", "CrmCode")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_mapping_crm_code");

                    b.HasIndex("TenantId", "ConnectionId", "Domain", "ExternalCode")
                        .HasDatabaseName("ix_integration_mapping_external_code");

                    b.ToTable("integration_mapping", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationReconciliationGap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<Guid?>("CrmId")
                        .HasColumnType("uuid")
                        .HasColumnName("crm_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("GapType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("gap_type");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resolution");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_integration_reconciliation_gap");

                    b.HasIndex("TenantId", "Resolution")
                        .HasDatabaseName("ix_integration_reconciliation_gap_tenant_resolution");

                    b.HasIndex("TenantId", "ConnectionId", "GapType", "CrmId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_reconciliation_gap_open")
                        .HasFilter("resolution = 'Open'");

                    b.ToTable("integration_reconciliation_gap", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CheckedCount")
                        .HasColumnType("integer")
                        .HasColumnName("checked_count");

                    b.Property<int>("ClosedCount")
                        .HasColumnType("integer")
                        .HasColumnName("closed_count");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("FailureDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_detail");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("GapCount")
                        .HasColumnType("integer")
                        .HasColumnName("gap_count");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_integration_reconciliation_run");

                    b.HasIndex("TenantId", "StartedAt")
                        .HasDatabaseName("ix_integration_reconciliation_run_tenant_started");

                    b.ToTable("integration_reconciliation_run", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CrmId")
                        .HasColumnType("uuid")
                        .HasColumnName("crm_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_integration_reference");

                    b.HasIndex("TenantId", "ConnectionId", "EntityType", "CrmId")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_reference_crm");

                    b.HasIndex("TenantId", "ConnectionId", "EntityType", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_reference_external");

                    b.ToTable("integration_reference", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationRelayAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CertificateIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certificate_issued_at");

                    b.Property<string>("CertificateThumbprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("certificate_thumbprint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EnrolmentTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolment_token_expires_at");

                    b.Property<string>("EnrolmentTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("enrolment_token_hash");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int?>("ReportedLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("reported_latency_ms");

                    b.Property<string>("ReportedStatusDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reported_status_detail");

                    b.Property<string>("ReportedTargetsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("reported_targets");

                    b.Property<string>("ReportedVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reported_version");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_integration_relay_agent");

                    b.HasIndex("CertificateThumbprint")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_relay_agent_certificate")
                        .HasFilter("certificate_thumbprint IS NOT NULL");

                    b.HasIndex("EnrolmentTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_relay_agent_enrolment_token")
                        .HasFilter("enrolment_token_hash IS NOT NULL");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_integration_relay_agent_tenant_status");

                    b.ToTable("integration_relay_agent", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.IntegrationSyncCursor", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("Stream")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("stream");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<string>("Cursor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cursor");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TenantId", "ConnectionId", "Stream")
                        .HasName("pk_integration_sync_cursor");

                    b.ToTable("integration_sync_cursor", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Domain.KycLimitAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Ceiling")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ceiling");

                    b.Property<Guid>("CrmCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("crm_customer_id");

                    b.Property<string>("LimitKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("limit_kind");

                    b.Property<decimal>("Observed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("observed");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_integration_kyc_limit_alert");

                    b.HasIndex("TenantId", "RaisedAt")
                        .HasDatabaseName("ix_integration_kyc_limit_alert_tenant_raised");

                    b.HasIndex("TenantId", "CrmCustomerId", "LimitKind", "Severity", "Period")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_kyc_limit_alert_period");

                    b.ToTable("integration_kyc_limit_alert", "integration");
                });

            modelBuilder.Entity("Sankore.Modules.Integration.Infrastructure.IntegrationInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("TenantId", "ReceivedAt")
                        .HasDatabaseName("ix_integration_inbox_tenant_received");

                    b.ToTable("inbox_messages", "integration");
                });

            modelBuilder.Entity("Sankore.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_occurred_at");

                    b.ToTable("outbox_messages", "integration");
                });
#pragma warning restore 612, 618
        }
    }
}
